### ISSUE TITLE
Chem-master, PACMAN, cloning console, presumably more interfaces bugged

### ISSUE THREAD

**Issue by triplezeta** [Haven-13/Haven-Urist#84]
#### Description of issue

Many, many interfaces did not work in an intended way. These were just the ones I saw in testing.

#### Difference between expected and actual behavior

Interfaces should've functioned like normal, instead:

PACMAN interface failed to load entirely.
Chem-master and cloning console loaded (as HTML interfaces, unsure if this is intentional) but clicking on links (buttons?) failed to do anything.

#### Specific information for locating

just try using the machines

#### Length of time in which bug has been known to occur

now

#### Client version, Server revision & Game ID

514.1557 for both client and server, no game ID because localhost but I should be able to retrieve logs

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues) **i didnt check lol**

**Comment by triplezeta** [comment]
gonna comment as I find more broken UIs:

Seed vendor (garden seed storage) has a broken HTML interface (links dont work) 

same for the holodeck

Microwave UI broken?

**Comment by triplezeta** [comment]
Air alarm TGUI interface is broken, submenus can be gone into but many buttons do not function properly (i.e. cannot set a vent to siphon)

**Comment by triplezeta** [comment]
![image](https://user-images.githubusercontent.com/51932018/134758987-6838a7b8-c78a-49f8-a07e-9248c84ef01b.png)

**Comment by triplezeta** [comment]
nuke broke

**Comment by martinlyra** [comment]
Closing this because I believe that all of the issues mentioned here are resolved. If one or more issues show up, please open a separate issue for every each one.
